# Digital Signal Processing
## Convolution and Correlation

### MsCV - ViBOT - MAIA

In [1]:
%matplotlib inline
%pprint off

# To make some nice plot
import matplotlib.pyplot as plt
# To play with arrays
import numpy as np
from skimage import io
from skimage import img_as_float
from matplotlib import cm

Pretty printing has been turned OFF


## Exercise 1- 1D Convolution

**1.1** Defining a signal $x$ and an impulse response $h$ as parameters, write a program `conv_fn` to compute the convolution product $y=h*x$. Do not use the python or matlab function and just consider zero padding to solve the border problem.

**1.2** Test your function, while using the following signal ($x[n] = \{\underline{1},2,3,4\}$) and following filters, ($\delta[k]$, $H[k]$, $e^{k}$, and $h = \{-1, 1\}$), respectively.

**1.3** Consider the previous input signal, write it's extended version while considering `symmetry`, `periodic` and `constant values` padding and $h = H[k-5]$



In [84]:
def conv_fn(x, h):
    x_pad = np.zeros((len(x) + 2*len(h),))
    x_pad[len(h)-1:len(h)+len(x)-1] = x.copy()
    y = np.zeros(len(x_pad))
    
   
    h = h[::-1]

    for i in range(0,len(x)+len(h)):
        h_pad = np.zeros(x_pad.shape)
        h_pad[i:len(h)+i] = h.copy()
        y[i] = np.sum(x_pad*h_pad)
        
    return y 
        

In [85]:
def dirac(n=0, N=20):
    if n > N - 1:
        raise ValueError('n should be in the range from 0 to N-1')
            
    s = np.zeros((N, ))
    s[n] = 1
    
    return s



In [86]:
def step(n=0, N=20):
    if n > N - 1:
        raise ValueError('n should be in the range from 0 to N-1')
    
    s = np.zeros((N, ))
    for n in range (n, N):
        s[n] = 1
    
    return s

In [89]:
x = np.array([1, 2, 3, 4])

h1 = dirac(N=5)

y = conv_fn(x, h)
print(y)
y1 = np.convolve(x,h)
print(y1)

h2 = step(N=5)

y2 = conv_fn(x, h2)
print(y2)
y3 = np.convolve(x, h2)
print(y3)

h3 = np.array([-1,0,1])
y4 = conv_fn(x, h3)
print(y4)
y5 = np.convolve(x, h3)
print(y5)


[ 1.  2.  3.  4.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  2.  3.  4.  0.  0.  0.  0.]
[  1.   3.   6.  10.  10.   9.   7.   4.   0.   0.   0.   0.   0.   0.]
[  1.   3.   6.  10.  10.   9.   7.   4.]
[-1. -2. -2. -2.  3.  4.  0.  0.  0.  0.]
[-1 -2 -2 -2  3  4]


## Exercise 2- 2D Convolution

**2.1** Define a 2D convolution function (Only consider zero-padding the image)

**2.2** Using your function, smooth the `lena` image with the following Gaussian kernel:
$$ K = \frac{1.}{256}\begin{bmatrix} 1 & 4 & 6 & 4 & 1 \\ 4 & 16 & 24 & 16 & 4 \\ 6 & 24 & 36 & 24 & 6 \\ 4 & 16 & 24 & 16 & 4 \\ 1 & 4 & 6 & 4 & 1 \end{bmatrix}$$

**2.3** Apply sobel filtering using convolution


In [10]:
def conv_fn2()

## Exercise 3 - Character recognition using cross-correlation

**3.1** load `a.png` and `text.png` images and binarized them using [`threshold_otsu`](http://scikit-image.org/docs/dev/api/skimage.filters.html?highlight=filters#skimage.filters.threshold_otsu)

**3.2** Use [`signal.correlate2d`](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.signal.correlate2d.html#scipy.signal.correlate2d) from `scipy` to correlate your binarized images.
**Note, signal correspond to the bright pixels within and image (invert your masks)**

**3.3** Find the first 10 characters recognized as `a`.